apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-anomaly-deployment
  labels:
    app: test-anomaly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-anomaly
  template:
    metadata:
      labels:
        app: test-anomaly
    spec:
      containers:
        - name: test-container
          image: busybox
          command: ["sh", "-c", "exit 1"] # Container will exit immediately
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
